# Generated by Django 4.0.1 on 2022-01-13 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_category_options_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
